#!/usr/bin/env sh

function gitcreateinfo () {
	echo "Creates a repository via the API"
	echo "git create <repo name> <repo description>"
}

function gitrepo () {
	curl -X "POST" -H "Authorization: token $(git config --global --get repo.gitcafe.api.token)" \
	-H "content-type: application/json" \
	$(git config --global --get repo.gitcafe.api.repos)  \
	-d "{
	  \"name\": \"${1}\",
	  \"title\": \"${2}\",
	  \"private\": true
	}" 2>/dev/null | jq
}

## Execution starts here
# I don't want no commands
if [ $# -ne 2 ]; then
	gitcreateinfo
	exit 127
fi

gitrepo "$@"
