#!/usr/bin/env sh

function gitcafelistinfo () {
	echo "List all repos in gitcafe via the API"
	echo "git cafelist"
}

function gitrepo () {
	curl -X "GET" -H "Authorization: token $(git config --global --get repo.gitcafe.api.token)" \
	$(git config --global --get repo.gitcafe.api.repos)  2>/dev/null | jq -r '.[].name' |sort
}

## Execution starts here
# I don't want no commands
if [ $# -ne 0 ]; then
	gitcafelistinfo
	exit 127
fi

gitrepo "$@"
